spring:
  exception:
    debug: true
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:test # test 부분을 자신이 원하는 것으로 바꾸시면 됩니다. 
    username: sa # username과 password는 자신의 설정에 맞게
    password: ""
    driver-class-name: org.h2.Driver
  # datasource:
  #   url: jdbc:mysql://localhost:3306/test # test 부분을 자신이 원하는 것으로 바꾸시면 됩니다. 
  #   username: root # username과 password는 자신의 설정에 맞게
  #   password: test
  #   driver-class-name: com.mysql.cj.jdbc.Driver

#     spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.datasource.url=jdbc:mysql://127.0.0.1:3306/[데이터베이스 이름]
# spring.datasource.username=[이름]
# spring.datasource.password=[비밀번호]


  jpa:
    hibernate:
      ddl-auto: create # 어플리케이션을 시작할 때 데이터베이스를 초기화하고 다시 테이블 생성
    properties:
      hibernate:
        format_sql: true # 실행되는 query를 보여줌
        # dialect: org.hibernate.dialect.MySQLDialect
    
  redis:
    host: localhost
    port: 6379

logging.level:
  org.hibernate.SQL: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml